package via.sep4;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import via.sep4.model.Room.Room;
import via.sep4.model.Room.RoomRepository;
import via.sep4.model.Sensor.Sensor;
import via.sep4.model.Sensor.SensorRepository;
import via.sep4.model.Sensor.SensorType;
import via.sep4.model.SensorHistory.SensorHistory;
import via.sep4.model.SensorHistory.SensorHistoryRepository;

import java.sql.Timestamp;

/**
 * The type Load database.
 */
@Configuration
public class LoadDatabase {


    /**
     * Init database command line runner. Inserts information into the database.
     *
     * @param sensorRepository        the sensor repository
     * @param roomRepository          the room repository
     * @param sensorHistoryRepository the sensor history repository
     * @return the command line runner
     */
    @Bean
    CommandLineRunner initDatabase(SensorRepository sensorRepository, RoomRepository roomRepository, SensorHistoryRepository sensorHistoryRepository) {
        return args -> {
            Room room0 = new Room("Freezer");
            Room room1 = new Room("Main");
            roomRepository.save(room0);
            roomRepository.save(room1);

            Sensor sensor0 = new Sensor(SensorType.CO2, "PPM", room0, 0, 0);
            Sensor sensor1 = new Sensor(SensorType.HUMIDITY, "%", room0, 0, 0);
            Sensor sensor2 = new Sensor(SensorType.TEMPERATURE, "°C", room0, 0, 30);
            Sensor sensor3 = new Sensor(SensorType.CO2, "PPM", room1, 0, 0);
            Sensor sensor4 = new Sensor(SensorType.HUMIDITY, "%", room1, 0, 0);
            Sensor sensor5 = new Sensor(SensorType.TEMPERATURE, "°C", room1, 0, 30);
            sensorRepository.save(sensor0);
            sensorRepository.save(sensor1);
            sensorRepository.save(sensor2);
            sensorRepository.save(sensor3);
            sensorRepository.save(sensor4);
            sensorRepository.save(sensor5);

            Timestamp timestamp0 = Timestamp.valueOf("2021-05-25 10:17:33.097");
            SensorHistory history0 = new SensorHistory(sensor0, timestamp0, 392);
            Timestamp timestamp1 = Timestamp.valueOf("2021-05-25 20:17:33.097");
            SensorHistory history1 = new SensorHistory(sensor0, timestamp1, 385);
            Timestamp timestamp2 = Timestamp.valueOf("2021-05-26 10:17:33.097");
            SensorHistory history2 = new SensorHistory(sensor0, timestamp2, 362);
            Timestamp timestamp3 = Timestamp.valueOf("2021-05-26 20:17:33.097");
            SensorHistory history3 = new SensorHistory(sensor0, timestamp3, 325);
            Timestamp timestamp4 = Timestamp.valueOf("2021-05-27 10:17:33.097");
            SensorHistory history4 = new SensorHistory(sensor0, timestamp4, 624);
            Timestamp timestamp5 = Timestamp.valueOf("2021-05-27 20:17:33.097");
            SensorHistory history5 = new SensorHistory(sensor0, timestamp5, 837);
            Timestamp timestamp6 = Timestamp.valueOf("2021-05-28 10:17:33.097");
            SensorHistory history6 = new SensorHistory(sensor0, timestamp6, 392);
            Timestamp timestamp7 = Timestamp.valueOf("2021-05-28 20:17:33.097");
            SensorHistory history7 = new SensorHistory(sensor0, timestamp7, 385);
            Timestamp timestamp8 = Timestamp.valueOf("2021-05-29 10:17:33.097");
            SensorHistory history8 = new SensorHistory(sensor0, timestamp8, 706);
            Timestamp timestamp9 = Timestamp.valueOf("2021-05-29 20:17:33.097");
            SensorHistory history9 = new SensorHistory(sensor0, timestamp9, 679);
            Timestamp timestamp10 = Timestamp.valueOf("2021-05-30 10:17:33.097");
            SensorHistory history10 = new SensorHistory(sensor0, timestamp10, 522);
            Timestamp timestamp11 = Timestamp.valueOf("2021-05-30 20:17:33.097");
            SensorHistory history11 = new SensorHistory(sensor0, timestamp11, 500);
            Timestamp timestamp12 = Timestamp.valueOf("2021-05-31 10:17:33.097");
            SensorHistory history12 = new SensorHistory(sensor0, timestamp12, 392);
            Timestamp timestamp13 = Timestamp.valueOf("2021-05-31 20:17:33.097");
            SensorHistory history13 = new SensorHistory(sensor0, timestamp13, 350);
            Timestamp timestamp14 = Timestamp.valueOf("2021-06-01 10:17:33.097");
            SensorHistory history14 = new SensorHistory(sensor0, timestamp14, 380);
            Timestamp timestamp15 = Timestamp.valueOf("2021-06-01 20:17:33.097");
            SensorHistory history15 = new SensorHistory(sensor0, timestamp15, 385);
            Timestamp timestamp16 = Timestamp.valueOf("2021-06-02 10:17:33.097");
            SensorHistory history16 = new SensorHistory(sensor0, timestamp16, 402);
            Timestamp timestamp17 = Timestamp.valueOf("2021-06-02 20:17:33.097");
            SensorHistory history17 = new SensorHistory(sensor0, timestamp17, 394);
            Timestamp timestamp18 = Timestamp.valueOf("2021-06-03 10:17:33.097");
            SensorHistory history18 = new SensorHistory(sensor0, timestamp18, 423);
            Timestamp timestamp19 = Timestamp.valueOf("2021-06-03 20:17:33.097");
            SensorHistory history19 = new SensorHistory(sensor0, timestamp19, 456);
            SensorHistory history20 = new SensorHistory(sensor3, timestamp0, 392);
            SensorHistory history21 = new SensorHistory(sensor3, timestamp1, 400);
            SensorHistory history22 = new SensorHistory(sensor3, timestamp2, 362);
            SensorHistory history23 = new SensorHistory(sensor3, timestamp3, 368);
            SensorHistory history24 = new SensorHistory(sensor3, timestamp4, 650);
            SensorHistory history25 = new SensorHistory(sensor3, timestamp5, 837);
            SensorHistory history26 = new SensorHistory(sensor3, timestamp6, 320);
            SensorHistory history27 = new SensorHistory(sensor3, timestamp7, 385);
            SensorHistory history28 = new SensorHistory(sensor3, timestamp8, 706);
            SensorHistory history29 = new SensorHistory(sensor3, timestamp9, 754);
            SensorHistory history30 = new SensorHistory(sensor3, timestamp10, 522);
            SensorHistory history31 = new SensorHistory(sensor3, timestamp11, 531);
            SensorHistory history32 = new SensorHistory(sensor3, timestamp12, 405);
            SensorHistory history33 = new SensorHistory(sensor3, timestamp13, 350);
            SensorHistory history34 = new SensorHistory(sensor3, timestamp14, 362);
            SensorHistory history35 = new SensorHistory(sensor3, timestamp15, 385);
            SensorHistory history36 = new SensorHistory(sensor3, timestamp16, 415);
            SensorHistory history37 = new SensorHistory(sensor3, timestamp17, 394);
            SensorHistory history38 = new SensorHistory(sensor3, timestamp18, 423);
            SensorHistory history39 = new SensorHistory(sensor3, timestamp19, 479);
            SensorHistory history40 = new SensorHistory(sensor1, timestamp0, 40.89);
            SensorHistory history41 = new SensorHistory(sensor1, timestamp1, 40.60);
            SensorHistory history42 = new SensorHistory(sensor1, timestamp2, 41);
            SensorHistory history43 = new SensorHistory(sensor1, timestamp3, 40.63);
            SensorHistory history44 = new SensorHistory(sensor1, timestamp4, 40.85);
            SensorHistory history45 = new SensorHistory(sensor1, timestamp5, 39.98);
            SensorHistory history46 = new SensorHistory(sensor1, timestamp6, 40.61);
            SensorHistory history47 = new SensorHistory(sensor1, timestamp7, 40.36);
            SensorHistory history48 = new SensorHistory(sensor1, timestamp8, 40.69);
            SensorHistory history49 = new SensorHistory(sensor1, timestamp9, 40.94);
            SensorHistory history50 = new SensorHistory(sensor1, timestamp10, 41.02);
            SensorHistory history51 = new SensorHistory(sensor1, timestamp11, 40.63);
            SensorHistory history52 = new SensorHistory(sensor1, timestamp12, 40.5);
            SensorHistory history53 = new SensorHistory(sensor1, timestamp13, 40.68);
            SensorHistory history54 = new SensorHistory(sensor1, timestamp14, 40.21);
            SensorHistory history55 = new SensorHistory(sensor1, timestamp15, 40.92);
            SensorHistory history56 = new SensorHistory(sensor1, timestamp16, 41.5);
            SensorHistory history57 = new SensorHistory(sensor1, timestamp17, 40.32);
            SensorHistory history58 = new SensorHistory(sensor1, timestamp18, 40.23);
            SensorHistory history59 = new SensorHistory(sensor1, timestamp19, 40.79);
            SensorHistory history60 = new SensorHistory(sensor4, timestamp0, 40.09);
            SensorHistory history61 = new SensorHistory(sensor4, timestamp1, 40.20);
            SensorHistory history62 = new SensorHistory(sensor4, timestamp2, 41.12);
            SensorHistory history63 = new SensorHistory(sensor4, timestamp3, 40.68);
            SensorHistory history64 = new SensorHistory(sensor4, timestamp4, 40.65);
            SensorHistory history65 = new SensorHistory(sensor4, timestamp5, 40.98);
            SensorHistory history66 = new SensorHistory(sensor4, timestamp6, 40.21);
            SensorHistory history67 = new SensorHistory(sensor4, timestamp7, 40.86);
            SensorHistory history68 = new SensorHistory(sensor4, timestamp8, 40.63);
            SensorHistory history69 = new SensorHistory(sensor4, timestamp9, 40.24);
            SensorHistory history70 = new SensorHistory(sensor4, timestamp10, 41.62);
            SensorHistory history71 = new SensorHistory(sensor4, timestamp11, 40.93);
            SensorHistory history72 = new SensorHistory(sensor4, timestamp12, 40.25);
            SensorHistory history73 = new SensorHistory(sensor4, timestamp13, 40.78);
            SensorHistory history74 = new SensorHistory(sensor4, timestamp14, 40.31);
            SensorHistory history75 = new SensorHistory(sensor4, timestamp15, 40.42);
            SensorHistory history76 = new SensorHistory(sensor4, timestamp16, 40.5);
            SensorHistory history77 = new SensorHistory(sensor4, timestamp17, 41.32);
            SensorHistory history78 = new SensorHistory(sensor4, timestamp18, 41.23);
            SensorHistory history79 = new SensorHistory(sensor4, timestamp19, 40.99);
            SensorHistory history80 = new SensorHistory(sensor2, timestamp0, -10.3);
            SensorHistory history81 = new SensorHistory(sensor2, timestamp1, -15);
            SensorHistory history82 = new SensorHistory(sensor2, timestamp2, -6.58);
            SensorHistory history83 = new SensorHistory(sensor2, timestamp3, -9.6);
            SensorHistory history84 = new SensorHistory(sensor2, timestamp4, -11);
            SensorHistory history85 = new SensorHistory(sensor2, timestamp5, -8.41);
            SensorHistory history86 = new SensorHistory(sensor2, timestamp6, -9.3);
            SensorHistory history87 = new SensorHistory(sensor2, timestamp7, -8);
            SensorHistory history88 = new SensorHistory(sensor2, timestamp8, -9.3);
            SensorHistory history89 = new SensorHistory(sensor2, timestamp9, -4.98);
            SensorHistory history90 = new SensorHistory(sensor2, timestamp10, -4.102);
            SensorHistory history91 = new SensorHistory(sensor2, timestamp11, -13.2);
            SensorHistory history92 = new SensorHistory(sensor2, timestamp12, -15.03);
            SensorHistory history93 = new SensorHistory(sensor2, timestamp13, -12.6);
            SensorHistory history94 = new SensorHistory(sensor2, timestamp14, -11.9);
            SensorHistory history95 = new SensorHistory(sensor2, timestamp15, -10.23);
            SensorHistory history96 = new SensorHistory(sensor2, timestamp16, -7.96);
            SensorHistory history97 = new SensorHistory(sensor2, timestamp17, -9.36);
            SensorHistory history98 = new SensorHistory(sensor2, timestamp18, -8.89);
            SensorHistory history99 = new SensorHistory(sensor2, timestamp19, -10.023);
            SensorHistory history100 = new SensorHistory(sensor5, timestamp0, 20.89);
            SensorHistory history101 = new SensorHistory(sensor5, timestamp1, 20.60);
            SensorHistory history102 = new SensorHistory(sensor5, timestamp2, 19);
            SensorHistory history103 = new SensorHistory(sensor5, timestamp3, 19.63);
            SensorHistory history104 = new SensorHistory(sensor5, timestamp4, 19.85);
            SensorHistory history105 = new SensorHistory(sensor5, timestamp5, 20.98);
            SensorHistory history106 = new SensorHistory(sensor5, timestamp6, 18.61);
            SensorHistory history107 = new SensorHistory(sensor5, timestamp7, 19.36);
            SensorHistory history108 = new SensorHistory(sensor5, timestamp8, 20.69);
            SensorHistory history109 = new SensorHistory(sensor5, timestamp9, 20.94);
            SensorHistory history110 = new SensorHistory(sensor5, timestamp10, 19.02);
            SensorHistory history111 = new SensorHistory(sensor5, timestamp11, 20.63);
            SensorHistory history112 = new SensorHistory(sensor5, timestamp12, 20.5);
            SensorHistory history113 = new SensorHistory(sensor5, timestamp13, 20.68);
            SensorHistory history114 = new SensorHistory(sensor5, timestamp14, 20.21);
            SensorHistory history115 = new SensorHistory(sensor5, timestamp15, 19.92);
            SensorHistory history116 = new SensorHistory(sensor5, timestamp16, 19.5);
            SensorHistory history117 = new SensorHistory(sensor5, timestamp17, 20.32);
            SensorHistory history118 = new SensorHistory(sensor5, timestamp18, 20.23);
            SensorHistory history119 = new SensorHistory(sensor5, timestamp19, 20.79);
            sensorHistoryRepository.save(history0);
            sensorHistoryRepository.save(history1);
            sensorHistoryRepository.save(history2);
            sensorHistoryRepository.save(history3);
            sensorHistoryRepository.save(history4);
            sensorHistoryRepository.save(history5);
            sensorHistoryRepository.save(history6);
            sensorHistoryRepository.save(history7);
            sensorHistoryRepository.save(history8);
            sensorHistoryRepository.save(history9);
            sensorHistoryRepository.save(history10);
            sensorHistoryRepository.save(history11);
            sensorHistoryRepository.save(history12);
            sensorHistoryRepository.save(history13);
            sensorHistoryRepository.save(history14);
            sensorHistoryRepository.save(history15);
            sensorHistoryRepository.save(history16);
            sensorHistoryRepository.save(history17);
            sensorHistoryRepository.save(history18);
            sensorHistoryRepository.save(history19);
            sensorHistoryRepository.save(history20);
            sensorHistoryRepository.save(history21);
            sensorHistoryRepository.save(history22);
            sensorHistoryRepository.save(history23);
            sensorHistoryRepository.save(history24);
            sensorHistoryRepository.save(history25);
            sensorHistoryRepository.save(history26);
            sensorHistoryRepository.save(history27);
            sensorHistoryRepository.save(history28);
            sensorHistoryRepository.save(history29);
            sensorHistoryRepository.save(history30);
            sensorHistoryRepository.save(history31);
            sensorHistoryRepository.save(history32);
            sensorHistoryRepository.save(history33);
            sensorHistoryRepository.save(history34);
            sensorHistoryRepository.save(history35);
            sensorHistoryRepository.save(history36);
            sensorHistoryRepository.save(history37);
            sensorHistoryRepository.save(history38);
            sensorHistoryRepository.save(history39);
            sensorHistoryRepository.save(history40);
            sensorHistoryRepository.save(history41);
            sensorHistoryRepository.save(history42);
            sensorHistoryRepository.save(history43);
            sensorHistoryRepository.save(history44);
            sensorHistoryRepository.save(history45);
            sensorHistoryRepository.save(history46);
            sensorHistoryRepository.save(history47);
            sensorHistoryRepository.save(history48);
            sensorHistoryRepository.save(history49);
            sensorHistoryRepository.save(history50);
            sensorHistoryRepository.save(history51);
            sensorHistoryRepository.save(history52);
            sensorHistoryRepository.save(history53);
            sensorHistoryRepository.save(history54);
            sensorHistoryRepository.save(history55);
            sensorHistoryRepository.save(history56);
            sensorHistoryRepository.save(history57);
            sensorHistoryRepository.save(history58);
            sensorHistoryRepository.save(history59);
            sensorHistoryRepository.save(history60);
            sensorHistoryRepository.save(history61);
            sensorHistoryRepository.save(history62);
            sensorHistoryRepository.save(history63);
            sensorHistoryRepository.save(history64);
            sensorHistoryRepository.save(history65);
            sensorHistoryRepository.save(history66);
            sensorHistoryRepository.save(history67);
            sensorHistoryRepository.save(history68);
            sensorHistoryRepository.save(history69);
            sensorHistoryRepository.save(history70);
            sensorHistoryRepository.save(history71);
            sensorHistoryRepository.save(history72);
            sensorHistoryRepository.save(history73);
            sensorHistoryRepository.save(history74);
            sensorHistoryRepository.save(history75);
            sensorHistoryRepository.save(history76);
            sensorHistoryRepository.save(history77);
            sensorHistoryRepository.save(history78);
            sensorHistoryRepository.save(history79);
            sensorHistoryRepository.save(history80);
            sensorHistoryRepository.save(history81);
            sensorHistoryRepository.save(history82);
            sensorHistoryRepository.save(history83);
            sensorHistoryRepository.save(history84);
            sensorHistoryRepository.save(history85);
            sensorHistoryRepository.save(history86);
            sensorHistoryRepository.save(history87);
            sensorHistoryRepository.save(history88);
            sensorHistoryRepository.save(history89);
            sensorHistoryRepository.save(history90);
            sensorHistoryRepository.save(history91);
            sensorHistoryRepository.save(history92);
            sensorHistoryRepository.save(history93);
            sensorHistoryRepository.save(history94);
            sensorHistoryRepository.save(history95);
            sensorHistoryRepository.save(history96);
            sensorHistoryRepository.save(history97);
            sensorHistoryRepository.save(history98);
            sensorHistoryRepository.save(history99);
            sensorHistoryRepository.save(history100);
            sensorHistoryRepository.save(history101);
            sensorHistoryRepository.save(history102);
            sensorHistoryRepository.save(history103);
            sensorHistoryRepository.save(history104);
            sensorHistoryRepository.save(history105);
            sensorHistoryRepository.save(history106);
            sensorHistoryRepository.save(history107);
            sensorHistoryRepository.save(history108);
            sensorHistoryRepository.save(history109);
            sensorHistoryRepository.save(history110);
            sensorHistoryRepository.save(history111);
            sensorHistoryRepository.save(history112);
            sensorHistoryRepository.save(history113);
            sensorHistoryRepository.save(history114);
            sensorHistoryRepository.save(history115);
            sensorHistoryRepository.save(history116);
            sensorHistoryRepository.save(history117);
            sensorHistoryRepository.save(history118);
            sensorHistoryRepository.save(history119);
        };
    }
}
